### ISSUE TITLE
Cookie没有清除干净

### ISSUE THREAD

**Issue by cnblogsTim** [JoesWeek/Cnblogs#1]
您好,我在使用的时候，发现。我注销用户后，在点击登陆的时候，不用输入用户名和密码。直接就可以登陆了。我觉得这个是不合理的。希望能改进。退出登陆的时候。清除Cookie.

**Comment by JoesWeek** [comment]
@cnblogsTim 您好，这个是博客园方面的问题，我已经反馈给了博客园的技术人员了，感谢您的反馈。

**Comment by JoesWeek** [comment]
已修复
