### ISSUE TITLE
博客园是否有公开发博文的API接口？

### ISSUE THREAD

**Issue by redstoneleo** [JoesWeek/Cnblogs#2]
大大有做这个APP的经历，我想问问博客园是否有公开发博文的API接口？
我主要是想写代码把我的我网易轻博客LOFTER搬家到cnblogs

**Comment by JoesWeek** [comment]
好像没有发博文的接口。你可以试试博客园的搬家功能。

**Comment by redstoneleo** [comment]
可以有https://group.cnblogs.com/topic/77953.html
